### ISSUE TITLE
Roadmap to stable release

### ISSUE THREAD

**Issue by xf-** [catch-IT/grav-image-server#1]
### Current state

**Alpha** - at the moment
Allowing changes on the API/twig function (arguments and their order)

Next is properly stable after alpha. Testing it in a small project

### To-do

- [x]  Fully implement/test SVG support for classes
- [ ] Finish a first version of documentation
  - [x] Min requirement
  - [ ] Explain how images are working and all that wonderful stuff.
  - [ ] Add section about grav 1.8 (adapter/on demand images)
- [x] Wait for next admin release with patch for list defaults (works without, but more config effort)

### Nice2have

- [ ] Next Gen Editor support with presets on images. Easy to use for editor

### Maybe some feedback on current state
:)
